version: '3'
services:
  zeppelin:
    image: twang2218/zeppelin:all
    volumes:
      - zeppelin-data:/data
    ports:
      - "80:8080"
    environment:
        ZEPPELIN_MEM: "-Xmx3g"

volumes:
  zeppelin-data:
