version: '3'
services:
  zeppelin:
    image: twang2218/zeppelin:all
    volumes:
      - zeppelin-data:/data
    ports:
      - "8080:8080"
      - "4040:4040"
    tmpfs: /tmp
    environment:
        ZEPPELIN_MEM: "-Xmx4g"
        ZEPPELIN_INTP_MEM: "-Xmx4g"

volumes:
  zeppelin-data:
